-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id serial NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    address character varying NOT NULL,
    country character varying NOT NULL,
    city character varying NOT NULL,
    role_id integer NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.flight_ticket
(
    flight_ticket_id serial NOT NULL,
    date_of_creation date NOT NULL,
    reserved_seats integer NOT NULL,
    reservation_status character varying NOT NULL,
    customer_id integer NOT NULL,
    flight_id integer NOT NULL,
    PRIMARY KEY (flight_ticket_id)
);

CREATE TABLE IF NOT EXISTS public.flight
(
    flight_id serial NOT NULL,
    number_of_seats integer NOT NULL,
    available_seats integer NOT NULL,
    price double precision NOT NULL,
    flight_date date NOT NULL,
    airplane_id integer NOT NULL,
    air_company_id integer NOT NULL,
    destination_id integer NOT NULL,
    PRIMARY KEY (flight_id)
);

CREATE TABLE IF NOT EXISTS public.destination
(
    destination_id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (destination_id)
);

CREATE TABLE IF NOT EXISTS public.airplane
(
    airplane_id serial NOT NULL,
    seats integer NOT NULL,
    brand character varying NOT NULL,
    PRIMARY KEY (airplane_id)
);

CREATE TABLE IF NOT EXISTS public.air_company
(
    air_company_id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (air_company_id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    role_id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (role_id)
);

ALTER TABLE IF EXISTS public.customer
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
              NOT VALID;


ALTER TABLE IF EXISTS public.flight_ticket
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
              NOT VALID;


ALTER TABLE IF EXISTS public.flight_ticket
    ADD FOREIGN KEY (flight_id)
    REFERENCES public.flight (flight_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
              NOT VALID;


ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (destination_id)
    REFERENCES public.destination (destination_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
              NOT VALID;


ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (airplane_id)
    REFERENCES public.airplane (airplane_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
              NOT VALID;


ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (air_company_id)
    REFERENCES public.air_company (air_company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
              NOT VALID;

END;